#ktor:
#    application:
#        modules:
#            - com.example.ApplicationKt.module
#    deployment:
#        port: 8080



ktor:
    deployment:
        port: ${PORT}  # This will be provided by Heroku in production

    application:
        modules:
            - com.example.ApplicationKt.module

    environment:
        development:
            database:
                url: "jdbc:postgresql://localhost:5432/ktor_tutorial_db"
                user: "postgres"
                password: "samkitjain"
                driver: "org.postgresql.Driver"
        production:
            database:
                url: ${JDBC_DATABASE_URL}  # Provided by environment variables
                user: ${JDBC_DATABASE_USERNAME}
                password: ${JDBC_DATABASE_PASSWORD}
                driver: "org.postgresql.Driver"
